module.exports={
  black: 'black+white_bg',
  dark_blue: 'blue',
  dark_green: 'green',
  dark_aqua: 'cyan',
  dark_red: 'red',
  dark_purple: 'magenta',
  gold: 'yellow',
  gray: 'black+white_bg',
  dark_gray: 'black+white_bg',
  blue: 'blue',
  green: 'green',
  aqua: 'cyan',
  red: 'red',
  light_purple: 'magenta',
  yellow: 'yellow',
  white: 'white',
  obfuscated: 'blink',
  bold: 'bold',
  strikethrough: '',
  underlined: 'underlined',
  italic: '',
  reset: 'white+black_bg'
}